# Generated by Django 5.1.2 on 2024-12-01 20:54

import api.models
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_movie_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-added_at']},
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.IntegerField(validators=[api.models.validate_release_year]),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'movie')},
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'movie')},
        ),
    ]
